begin;
select plan(8);
select has_table('public', 'profiles', 'profiles table exists');
select col_is_pk('public', 'profiles', 'id', 'id is PK');
select col_type_is('public', 'profiles', 'id', 'uuid', 'id is uuid');
select col_type_is('public', 'profiles', 'display_name', 'text', 'display_name is text');
select col_not_null('public', 'profiles', 'display_name', 'display_name is required');
select col_is_null('public', 'profiles', 'phone', 'phone is optional');
select col_type_is('public', 'profiles', 'batting_style', 'batting_style', 'batting_style uses enum');
select has_index('public', 'profiles', 'profiles_phone_idx', 'phone is indexed for search');
select * from finish();
rollback;
